## Matrix Multiplicaion, Dot and Cross Product


<img width="30%" class="imgright" src="../images/abacus.webp" alt="Abacus">

Distorted Abacus In the previous chapter of our introduction in NumPy we have demonstrated how to create and change Arrays. In this chapter we want to show, how we can perform in Python with the module NumPy all the basic Matrix Arithmetics like

- Matrix addition
- Matrix subtraction
- Matrix multiplication
- Scalar product
- Cross product
- and lots of other operations on matrices



The arithemtic standard Operators

- +
- -
- *
- /
- **
- %

are applied on the elements, this means that the arrays have to have the same size.



In [2]:
import numpy as np

x = np.array([1, 5, 2])
y = np.array([7, 4, 1])
x + y

array([8, 9, 3])

In [3]:
x * y

array([ 7, 20,  2])

In [ ]:
x - y

In [4]:
x / y

array([0.14285714, 1.25      , 2.        ])

In [5]:
x % y

array([1, 1, 0])

### Vector Addition and Subtraction

<img class="imgright" src="../images/vector_addition.webp" srcset="../images/vector_addition_400w.webp 400w,../images/vector_addition_350w.webp 350w,../images/vector_addition_300w.webp 300w" alt="Graphical Example of Vector Addition">  
Many people know vector addition and subtraction from physics, to be exact from the 
parallelogram of forces. It is a method for solving (or visualizing) the results of 
applying two forces to an object. 
<br><br>
The addition of two vectors, in our example (see picture) x and y, may be represented 
graphically by placing the start of the arrow y at the tip of the arrow x, and then 
drawing an arrow from the start (tail) of x to the tip (head) of y. 
The new arrow drawn represents the vector x + y



In [6]:
x = np.array([3, 2])
y = np.array([5, 1])
z = x + y
z

array([8, 3])

<img class="imgright" src="../images/vector_subtraction.webp" srcset="../images/vector_subtraction_350w.webp 350w,../images/vector_subtraction_300w.webp 300w" alt="Graphical Example of Vector Subtraction">
Subtracting a vector is the same as adding its negative. So, the difference of the vectors x and y is equal to the sum of x and -y:
x - y = x + (-y)
Subtraction of two vectors can be geometrically defined as follows: to subtract y from x, we place the end points of x and y at the same point, and then draw an arrow from the tip of y to the tip of x. That arrow represents the vector x - y, see picture on the right side.

Mathematically, we subtract the corresponding components of vector y from the vector x. 

### Scalar Product / Dot Product

In mathematics, the dot product is an algebraic operation that takes two coordinate vectors of 
equal size and returns a single number. The result is calculated by multiplying corresponding 
entries and adding up those products. 
The name "dot product" stems from the fact that the centered dot "·" is often used to designate 
this operation. The name "scalar product" focusses on the scalar nature of the result.
 of the result.
<br><br>
Definition of the scalar product:
<br><br>
<img src="../images/scalar_product.webp" alt="Definition of the Scalar Product">
<br><br>
We can see from the definition of the scalar product that it can be used to calculate the cosine 
of the angle between two vectors. 
<br><br>
Calculation of the scalar product:
<br><br>
<img src="../images/scalar_product1.webp" alt="Calculation of the Scalar Product">
<br><br>
Finally, we want to demonstrate how to calculate the scalar product in Python:


In [9]:
x = np.array([1, 2, 3])
y = np.array([-7, 8, 9])
np.dot(x, y)

36

In [10]:
dot = np.dot(x ,y)
x_modulus = np.sqrt((x*x).sum())
y_modulus = np.sqrt((y*y).sum())
cos_angle = dot / x_modulus / y_modulus # cosine of angle between x and y
angle = np.arccos(cos_angle)
angle

0.808233789010825

In [11]:
angle * 360 / 2 / np.pi # angle in degrees

46.308384970187326

In [ ]:
36
>>> dot = np.dot(x,y)
>>> x_modulus = np.sqrt((x*x).sum())
>>> y_modulus = np.sqrt((y*y).sum())
>>> cos_angle = dot / x_modulus / y_modulus # cosine of angle between x and y
>>> angle = np.arccos(cos_angle)
>>> angle
0.80823378901082499
>>> angle * 360 / 2 / np.pi # angle in degrees

### Matrix Product

The matrix product of two matrices can be calculated if the number of columns of the left
matrix is equal to the number of rows of the second or right matrix. 
<br>
The product of a (l x m)-matrix A = (a<sub>ij</sub>)<sub>i=1...l, j= 1..m</sub>  and an 
(m x n)-matrix B = (b<sub>ij</sub>)<sub>i=1...m, j= 1..n</sub>  is a matrix 
C = (c<sub>ij</sub>)<sub>i=1...l, j= 1..n</sub>, which is calculated like this:
<br><br>
<img src="../images/matrix_product.webp" alt="Matrix Product">
<br><br>
The following picture illustrates it further:
<br>
<img src="../images/matrix_product2.webp" alt="Matrix Product Illustration" width="95%">
<br><br>
If we want to perform matrix multiplication with two numpy arrays (ndarray), we have to use the 
dot product:

In [12]:
x = np.array( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)) )
print(np.dot(x,y))

[[17  1]
 [28  1]]


### Simple Practical Application for Matrix Multiplication

<img class="imgright" src="../images/pralinen.webp" alt="Chocolates">
In the following practical example, we come to talk about the sweet things of life. <br>
Let's assume there are four people, and we call them Lucas, Mia, Leon and Hannah. Each of
them has bought chocolates out of a choice of three. The brand are A, B and C, not very
marketable, we have to admit. Lucas bought 100 g of brand A, 175 g of brand B and 210 of C.
Mia choose 90 g of A, 160 g of B and 150 g of C. Leon bought 200 g of A, 50 of B and
100 g of C. Hannah apparently didn't like brand B, because she hadn't bought any of those. But she
she seems to be a real fan of brand C, because she bought 310 g of them. Furthermore she 
bought 120 g of A.<br><br>
So, what's the price in Euro of these chocolates: A costs 2.98 per 100 g, B costs 3.90 and C only 
1.99 Euro.
<br><br> 
If we have to calculate how much each of them had to pay, we can use Python, NumPy and Matrix 
multiplication:
<br>

In [2]:
import numpy as np
NumPersons = np.array([[100, 175, 210],
                       [90, 160, 150],
                       [200, 50, 100],
                       [120, 0, 310]])
Price_per_100_g = np.array([2.98, 3.90, 1.99])
Price_in_Cent = np.dot(NumPersons,Price_per_100_g)
Price_in_Euro = Price_in_Cent / 100
Price_in_Euro


array([13.984, 11.907,  9.9  ,  9.745])

### Cross Product

<img class="imgright" src="../images/Cross_product_vector.webp" srcset="../images/Cross_product_vector_300w.webp 300w" alt="Vector cross product diagram">
Let's stop consuming delicious chocolates and come back to a more mathematical and less 
high-calorie topic, i.e. the cross product.
<br><br>
The cross product or vector product is a binary operation on two vectors in three-dimensional
space. The result is a vector which is perpendicular to the vectors being multiplied and 
normal to the plane containing them. 
<br><br>
The cross product of two vectors a and b is denoted by a × b.
<br><br>
It's defined as:
<br><br>
<img src="../images/cross_product_definition.webp" alt="Cross Product Definition">
<br>
where n is a unit vector perpendicular to the plane containing a and b in the direction 
given by the right-hand rule.
<br><br>
If either of the vectors being multiplied is zero or the vectors are parallel then their 
cross product is zero. More generally, the magnitude of the product equals the area of a 
parallelogram with the vectors as sides. If the vectors are perpendicular the parallelogram 
is a rectangle and the magnitude of the product is the product of their lengths. 


In [17]:
x = np.array([0, 0, 1])
y = np.array([0, 1, 0])

np.cross(x, y)

array([-1,  0,  0])

In [18]:
np.cross(y, x)

array([1, 0, 0])