## NumPy Arrays
<img width=600 src="Images/Arrays.png"/>

### Erzeugung und Typ der Elemente
NumPy - Arrays können aus kombinierten Typen von Kernpython erzeugt werden. Wir zeigen dies jetzt noch einmal für eine Liste und einen Tupel. Natürlich kann man auch einzelne Werte eingeben, es entsteht dann ein Array mit nur einem Element, man spricht dann von einem Skalar. Bei Mischungen von Typen zum Erzeugen von NumPy-Arrays werden, wenn auch Strings vorkommen, alle Elemente in Strings verwandelt.

In [2]:
import numpy as np
a1 = np.array([1,2,3,5])
a2 = np.array((4,6,7,8,9))
a3 = np.array(1) # Skalar
a4 = np.array("foo") # String - Skalar
print (a1,a2,a3,a4)
gemischt = np.array(["a",2,3])
print(f"Bei gemischten Typen der Elemente, wenn auch Strings vorkommen, werden alle Elemente in Strings überführt: {gemischt}")

[1 2 3 5] [4 6 7 8 9] 1 foo
Bei gemischten Typen der Elemente, wenn auch Strings vorkommen, werden alle Elemente in Strings überführt: ['a' '2' '3']


Welche Typen sind überhaupt in NumPy- Arrays erlaubt? Wir können Sie uns mit np.ScalarType anzeigen lassen.

In [12]:
np.ScalarType

(int,
 float,
 complex,
 int,
 bool,
 bytes,
 str,
 memoryview,
 numpy.bool_,
 numpy.complex64,
 numpy.clongdouble,
 numpy.complex128,
 numpy.float16,
 numpy.float32,
 numpy.longdouble,
 numpy.float64,
 numpy.int8,
 numpy.int16,
 numpy.int32,
 numpy.intc,
 numpy.int64,
 numpy.timedelta64,
 numpy.datetime64,
 numpy.object_,
 numpy.bytes_,
 numpy.str_,
 numpy.uint8,
 numpy.uint16,
 numpy.uintc,
 numpy.uint32,
 numpy.uint64,
 numpy.void)

 Neben den numerischen Typen, Boolschen Werten, Strings und dem Bytetyp aus Kernpython sind natürlich auch numerische Typen aus NumPy selber erlaubt, wobei die angefügten Zahlen die Anzahl von Bits angeben, die die maximale Länge der Zahlen beschreibt. Eine genaue Definition der Typen findet man bei https://numpy.org/doc/stable/reference/arrays.scalars.html.
Der "long" Namensbestandteil verweist ebenfalls auf erhöhte Prezision beim Speichern der Zahl. Der "u" Bestandteil steht für "unsigned" also Zahlen ohne Vorzeichen. Der Maximalwert für diese Integer erhöht sich damit auf das Doppelte, z.B. 0 bis 65535 für uint16 statt -32768 bis 32767 für int16. Wie man sieht, sind auch Zeit- und Datumstypen erlaubt (timedelta64,
datetime64). "void" erlaubt die Eingabe von flexiblen Datentypen, wie zum Beispiel Strukturen (kombinierte Datentypen) aus anderen Sprachen (C), deren einzelne Einträge zu verschiedenen Datentypen gehören können. Mit memoryviews lassen sich Speicher-Puffer direkt bearbeiten, die Array Daten verschiedenster Art enthalten können. Die zahlreichen NumPy-Typen sind  auch daraus ausgerichtet, Daten aus anderen Programmiersprachen (z.B. C) einfach und kompatibel verarbeiten zu können. Sie sind z.T. Plattform-spezifisch, im Einzelfall sollte man immer die Dokumentation bemühen, wenn ein solches Übernahmeproblem besteht. <br>
Interessant ist noch der Datentyp "object". Hiermit können <b>alle</b> Python-Objekte abgespeichert werden, wie untenstehendes Beispiel mit Klasseninstanzen zeigt. Mit dtype = xxxx als zweitem Argument in der Arraydeklaration können wir den entsprechenden Typ erzwingen, wie unten im zweiten Beispiel gezeigt. <b>Verwendet man keine dtype - Angabe, erschliesst NumPy den benötigten Wert aus den Eingabedaten. </b> 

In [3]:
zahlen = np.array ([1.2,3.4,5.6])
print(zahlen)
zahlen_int = np.array ([1.2,3.4,5.6],dtype = np.int8)
print(zahlen_int)

class test:
    pass
    
a = test()
b = test()
np.array([a,b],dtype = object)
        


[1.2 3.4 5.6]
[1 3 5]


array([<__main__.test object at 0x000002596AEC2A30>,
       <__main__.test object at 0x000002596AEC2160>], dtype=object)

Man kann also beim Anlegen eines NumPy- Arrays den Datentyp mit angeben über das dtype Schlüsselwort. Dies hat natürlich Einfluss auf den Speicherbedarf der Arrays. Mit der  ```dtype``` Methode kann man sich den Typ eines NumPy-Objektes ausgeben lassen. 

In [28]:
kleine_int = np.array(list(range(100)),dtype = np.int8)
print(kleine_int.__sizeof__())
mittlere_int = np.array(list(range(100)),dtype = np.int16)
print(mittlere_int.__sizeof__())
mittlere_int.dtype

204
304


dtype('int16')

Was passiert, wenn man den erlaubten Bereich des Typs überschreitet bei der Eingabe?

In [5]:
print(np.power(100, 8, dtype = np.int64)) # 100 hoch 8
print(f"Zu kleiner dtype erzeugt Fehler, Maximalwert wäre 127 für 100**8 Ausgabe: {np.power(100, 8, dtype = np.int8)}")


10000000000000000
Zu kleiner dtype erzeugt Fehler, Maximalwert wäre 127 für 100**8 Ausgabe: 0


In [ ]:
Man kann ein np.dtype-Objekt auch selber konstruieren, wie unten gezeigt.

In [6]:
alle_zu_0_bis_255 = np.dtype(np.uint8)
print(alle_zu_0_bis_255)

my_list =  [115, 230.9, 229.2, 234]
my_list2 = [115, 230.9, 229.2, 234, 566]
A = np.array(my_list, dtype=alle_zu_0_bis_255)
B = np.array(my_list2, dtype=alle_zu_0_bis_255)
print(A)
print(f"Fehler des letzen Elements 566, da Bereichsüberschreitung=! {B}")

uint8
[115 230 229 234]
Fehler des letzen Elements 566, da Bereichsüberschreitung=! [115 230 229 234  54]


Interessant wird dies vor allem bei Arrays mit gemischten Typen, sogenannten strukturierten Arrays. ```dtype``` erlaubt uns dann , spaltenweise Typen zu deklarieren. Auf die einzelnen Spalten können wir mit dem Spaltennamen zugreifen und deren Elemente auch indizieren. <b>Mehr zu strukturierten Arrays später.

In [117]:
mixed_type = np.dtype([("Integerzahlen",np.int8),
                      ("Floats",np.float16),
                      ("Strings","U10")])

mixed= np.array([
                (12,3.4,"Hallo"),
                (-17,34567.8,"Foo"),
                (34,3.1415926,"Bar"),
                ],
                dtype = mixed_type)

print(f"Das ganze Array: {mixed}")
print(f"Die Spalte 'Integerzahlen': {mixed['Integerzahlen']}")
print(f"Die Spalte 'Integerzahlen'  mit ihrem 1.Element: {mixed['Integerzahlen'][0]}\n\n")





Das ganze Array: [( 12, 3.400e+00, 'Hallo') (-17, 3.456e+04, 'Foo') ( 34, 3.141e+00, 'Bar')]
Die Spalte 'Integerzahlen': [ 12 -17  34]
Die Spalte 'Integerzahlen'  it ihrem 1.Element: 12




Neben den hier gezeigten Methoden um ein np.array zu erzeugen gibt es noch andere wichtige Möglichkeiten. Zunäachst können wir Arrays mit Nullen oder Einsen komplett auffüllen. Auch hierbei können wir den dtype eingeben, z.B. je nachdem ob die 0 oder 1 eine Integerzahl oder Float sein soll. Ausserdem braucht die entsprechende Methode np.zeros oder np.ones als erstes Argument die Form des Arrays, welches befüllt werden soll. Hier verwenden wir zunächst eindimensionale Arrays, mehrdimensionale Arrays werden später erklärt. Definieren wir ein Array, vom dem eine <b>Kopie mit derselben Form, allerdings mit Nullen oder Einsen aufgefüllt,</b> erstellt werden soll, geht das mit np.ones_like oder np.zeros_like.

In [97]:
länge = 10
a_mit_nullen_als_integer = np.zeros(länge,dtype = np.int8)
print(a_mit_nullen_als_integer)
a_mit_nullen_als_float = np.zeros(länge,dtype = np.float16)
print(a_mit_nullen_als_float)
a_mit_einsen_als_integer = np.ones(länge,dtype = np.int8)
print(a_mit_einsen_als_integer)
a_mit_einsen_als_float = np.ones(länge,dtype = np.float16)
print(a_mit_einsen_als_float)

print("="*60)
zu_kopierende_form = np.array(list(range(30)))
my_ones = np.ones_like(zu_kopierende_form)
print(my_ones)

my_zeros = np.zeros_like(zu_kopierende_form)
print(my_zeros)

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


### Arrays mit gleichen Abständen der Elemente
Ähnlich wie mit range() im Kernpython gibt es bei NumPy zwei Möglichkeiten Arrays mit Bereichen von Zahlen mit gleichen Intervallen (äquidistante Intervalle) zu erzeugen. Zunächst besprechen wir die np.arange() Methode mit folgender Syntax:<br><br>
```arange([start,] stop[, step], [, dtype=None])```

Sie ist analog zu range() von Python, allerdings ist der step als Schrittweite hier eine Float-Zahl. Die Benutzung der Start- und Stop-Parameter und deren Default-Werte entsprechen dem Verhalten in der range() Funktion, der Default-Wert von Step ist 1. Man kann einen dtype eingeben. Im Gegensatz zum Kernpython entsteht sofort das komplette Array. Man muss also nicht die Werte erst in eine Liste verwandeln. Wie bei range() endet die Erzeugung des Arrays ein Element <b>vor</b> dem Stop-Wert. Beachten muss man allerdings, dass Floatzahlen begrenzte Präzision haben, der Endwert könnte durch Ungenauigkeiten dann doch erreicht oder sogar überschritten werden. Beispiele folgen:

In [5]:
import numpy as np
integers_step_1 = np.arange(1, 7)
print(integers_step_1)
floats_step_1 = np.arange(1, 7, dtype = np.float16)
print(floats_step_1)
floats_step_einhalb = np.arange(1, 7,.5)
print(floats_step_einhalb)
test = np.arange(2.9, 3, 0.0000000005)
print(f" Hier wird durch den kleinen Step der Zielwert übersprungen: ... {test[-3:]}")


[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]
 Hier wird durch den kleinen Step der Zielwert übersprungen: ... [3.00000001 3.00000001 3.00000001]


Die andere Möglichkeit ist die Methode np.linspace() mit der Syntax:<br><br>
```linspace(start, stop, num=50, endpoint=True, retstep=False)```<br>
Hier erhalten wir eine vorgebene Anzahl ```num``` von Float-Werten  in unser Array zurückgegeben (default 50) im Bereich zwischen ```start``` und ```stop```. Der letzte Wert liegt entweder vor dem Wert ```stop```, wenn der ```endpoint```-Parameter nicht auf False gesetzt wird oder erreicht den ```stop```- Wert wenn ```endpoint``` True ist (default).<br>
```retstep``` gibt zusätzlich aus (in einem Tuple), wie die Intervallgrösse ist. (default = False)

In [12]:
print(f"mit Endpoint: {np.round(np.linspace(1,2,10),2)}")
print(f"ohne Endpoint: {np.linspace(1,2,10,endpoint = False)}")
print(f"Intervallgrösse: {np.linspace(1,2,10,retstep = True)}")

mit Endpoint: [1.   1.11 1.22 1.33 1.44 1.56 1.67 1.78 1.89 2.  ]
ohne Endpoint: [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
Intervallgrösse: (array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]), 0.1111111111111111)


### Array Dimensionen und Shape, Indizierung
Bisher haben wir uns mit NumPy-Arrays beschäftigt, die entweder nulldimensional (Skalare, also Einzelwert) oder eindimensional waren. NumPy-Arrays können aber auch beliebige zusätzliche Dimensionen umfassen. Man kann ein zweidimensionales Array einfach durch die Eingabe einer Liste von Listen (oder Tupel) erzeugen und sich mit ndim die Anzahl der Dimensionen anzeigen lassen. Mit shape kann man sich den Aufbau entlang der Achsen ansehen. Dabei ist bei unserem 2 dimensionalen Array die erste Dimension die Zahl der Reihen, die zweite die Zahl der Spalten. Die Angabe erfolgt als Tupel.

In [27]:
zwei_dim = np.array([
                    [1,2,3,9],
                    [4,5,6,7],
                    ]) # Liste von Listen
print(zwei_dim)    
print(f"zwei_dim hat {zwei_dim.ndim} Dimensionen, der Shape ist {zwei_dim.shape}")
ein_dim = np.array((1,2,3))
print(f"ein_dim hat  {ein_dim.ndim} Dimension, der Shape ist {ein_dim.shape}")
skalar = np.array(1)
print(f"skalar hat   {skalar.ndim} Dimensionen, der Shape ist {skalar.shape}")

[[1 2 3 9]
 [4 5 6 7]]
zwei_dim hat 2 Dimensionen, der Shape ist (2, 4)
ein_dim hat  1 Dimension, der Shape ist (3,)
skalar hat   0 Dimensionen, der Shape ist ()


Die Dimensionen im 3- dimensionalen Array zeigt das Bild:<br><br>
    <img width = 800 src="Images/ArrayDimensionen.png" />

Shape kann auch verwendet werden, um die Form eines Arrays zu verändern. Hierbei muss natürlich die Gesamtzahl der Elemente des Arrays gleich bleiben, sonst wird eine Exception ausgelöst.

In [39]:
print(zwei_dim)
print(60*"=")
zwei_dim.shape = (4,2)
print(zwei_dim)
# zwei_dim.shape = (3,3) Macht Fehler

[[1 2 3 9]
 [4 5 6 7]]
[[1 2]
 [3 9]
 [4 5]
 [6 7]]


Im Gegensatz zu shape, was das Originalarray verändert, macht reshape auf vergleichbare Weise ein neues Array, lässt aber das Original unverändert.

In [13]:
test_array = np.array([
                        [1,2,3,4],
                        [6,7,8,9],
                        [10,11,12,14],
                       ])

print(test_array,test_array.shape)
print(60*"=")
test_array.shape = (2,6)
print(f"originales test_array mit neuem shape: \n{test_array}")
test_array = np.array([
                        [1,2,3,4],
                        [6,7,8,9],
                        [10,11,12,14],
                       ])
new_array = test_array.reshape(12)

print(f" new_array nach reshape von originalem test_array: \n{new_array}")
print(f"originales test_array nach reshape: \n{test_array}")

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 14]] (3, 4)
originales test_array mit neuem shape: 
[[ 1  2  3  4  6  7]
 [ 8  9 10 11 12 14]]
 new_array nach reshape von originalem test_array: 
[ 1  2  3  4  6  7  8  9 10 11 12 14]
originales test_array nach reshape: 
[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 14]]


Verwendet man reshape mit dem Parameter -1 für eine Achse, macht NumPy automatisch eine passende Umwandlung über <b>alle</b> Elemente in dieser Achse. Ein Beispiel, was z.B. beim maschinellen Lernen häufig vorkommt, ist das Verwandeln eines 1-dimensionalen Arrays mit der Länge n in ein zweidimensionales Array mit n Zeilen und jeweils einem Eintrag. Dies kann man ohne Angabe der Länge des Arrays über eine solche Konstruktion durchführen mit Angabe von -1 für die Achse 0 (Zeilen).

In [2]:
import numpy as np
ein_dim = np.array(list(range(20)))
print (ein_dim)
neues_array = ein_dim.reshape(-1,1)
print (neues_array)
                   

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]



Mit einem Index (oder mehreren Indizes bei multidimensionalen Arrays) können wir auf einzelne Arrayelemente zugreifen. Hierzu gibt es zwei Möglichkeiten, die Indizes zu verketten:<br>
- Einmal:<b> array[Index1][Index2][Index...]</b> oder
- <b>array[Index1,Index2,Index...]</b><br><br>


Es gibt zwei somit Möglichkeiten, das gezeigte Element anzusprechen:<br>
<b>array [1][2][1]</b>
oder
<b>array [1,2,1]  Also: Ebene 1, Reihe 2 , Spalte 1.</b>
<br> Die 2. Möglichkeit ist aber effektiver, da intern nicht in jeder Dimension zuerst ein Teilarray aufgebaut wird, wie bei der ersten Methode.<br><br><img width=800 src="Images/ArrayDimensionenIndizes.png" /><br><br>
   


### Teilbereiche von Arrays
Teilbereiche lassen sich wie im Kernpython beschreiben mit ```[start,stop,step]```, wobei sich dies wie oben gezeigt dann in jeder Diemsion durchführen lässt und mit einfachen Indizes mischen lässt. So schneidet z.B. <b>zwei_dim[0,[0:3],[1:3]] </b> den gezeigten Bereich aus. Wir nehmen Reihe 0, die Spalten 0 bis vor 3, die Ebenen 1 bis vor 3.<br>
Den Bereich können wir sprachlich so definieren:<br>
Nimm die gesamte Ebene 0. Davon die Reihen 0, 1, 2. Davon die Spalten 1 und 2.
    

<img width = 800 src = "Images/ArrayDimensionenAusschnitt.png" />

In [23]:
zwei_dim = np.array([
                    [
                    [1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15],
                    [16,17,18,19,20],
                    ],
                    [
                    [-1,-2,-3,-4,-5],
                    [-6,-7,-8,-9,-10],
                    [-11,-12,-13,-14,-15],
                    [-16,-17,-18,-19,-20],
                    ],
                    [
                    [100,101,102,103,104],
                    [105,106,107,108,109],
                    [110,111,112,113,114],
                    [115,116,117,118,119],
                    ]
                    ]) 
    
    
    
    
    
    
    
    
print(zwei_dim)
print(zwei_dim[1,2,1])
print(zwei_dim[0])
zwei_dim[0,0:3,1:3]

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]]

 [[ -1  -2  -3  -4  -5]
  [ -6  -7  -8  -9 -10]
  [-11 -12 -13 -14 -15]
  [-16 -17 -18 -19 -20]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]]
-12
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

weitere Beispiele:

In [56]:
A = np.array([
[11, 12, 13, 14, 15, 16, 17, 18],
[21, 22, 23, 24, 25, 26, 27, 28],
[31, 32, 33, 34, 35, 36, 37, 38],
[41, 42, 43, 44, 45, 46, 47, 48],
[51, 52, 53, 54, 55, 56, 57, 58]])

print(A[:3, 2:5]) #alle Reihen von 0 bis vor 3 (2), davon alle Spalten von 2 bis vor 5 (4)

[[13 14]
 [23 24]
 [33 34]]


In [59]:
# Hier ein Beispiel mit step
print(A[1:3,::2]) #alle Reihen von 1 bis vor 3, davon alle Spalten, aber nur jede 2.

[[21 23 25 27]
 [31 33 35 37]]


In [60]:
print(A[3:1:-1,::2]) #alle Reihen von 3 bis vor 1 (3 und 2), davon jede 2. Spalte

[[41 43 45 47]
 [31 33 35 37]]


Lässt man Dimensionen im Ausschnittstupel weg, werden die restlichen Dimensionen als [:] angenommen.

In [29]:
drei_dim = np.array([
                        [
                        [1,2,3,4,5],
                        [6,7,8,9,10],
                        [11,12,23,45,17],
                        ],
                        [
                        [-1,-2,-3,-4,-5],
                        [-6,-7,-8,-9,-10],
                        [-11,-12,-23,-45,-17],
                        ],
                        [
                        [-100,-200,-300,-400,-500],
                        [-600,-700,-800,-900,-110],
                        [-111,-112,-123,-145,-117],
                        ]
                    ])
print(f"Alle Ebenen ,Reihen 1 und 2, alle Spalten drei_dim[:,1:3]:\n { drei_dim[:,1:3]}")
print(60*"=")
print(f"Ebenen 1 und 2 ,Reihen 2, alle Spalten drei_dim[1:3,2]:\n { drei_dim[1:3,2]}")
      

Alle Ebenen ,Reihen 1 und 2, alle Spalten drei_dim[:,1:3]:
 [[[   6    7    8    9   10]
  [  11   12   23   45   17]]

 [[  -6   -7   -8   -9  -10]
  [ -11  -12  -23  -45  -17]]

 [[-600 -700 -800 -900 -110]
  [-111 -112 -123 -145 -117]]]
Ebenen 1 und 2 ,Reihen 2, alle Spalten drei_dim[1:3,2]:
 [[ -11  -12  -23  -45  -17]
 [-111 -112 -123 -145 -117]]


### Arrays kopieren
Mit ```neues_array = array.copy() oder neues_array = np.copy(array)``` kann man eine echte Kopie eines Arrays erzeugen. Dann sind die beiden Arrays komplett unabhängig voneinander. 

In [77]:
drei_dim = np.array([
                        [
                        [1,2,3,4,5],
                        [6,7,8,9,10],
                        [11,12,23,45,17],
                        ],
                        [
                        [-1,-2,-3,-4,-5],
                        [-6,-7,-8,-9,-10],
                        [-11,-12,-23,-45,-17],
                        ],
                        [
                        [-100,-200,-300,-400,-500],
                        [-600,-700,-800,-900,-110],
                        [-111,-112,-123,-145,-117],
                        ]
                    ])
neu = drei_dim.copy("C")
print(f"Kopie ist: \n{neu}")
neu[1][2] = -10000
print(f"veränderte Kopie ist jetzt: \n{neu}")
print(f"Originalarray ist unverändert: \n{drei_dim}")
drei_dim[2][2] = -5
print(f"Originalarray ist verändert: \n{drei_dim}")
print(f"Kopie ist unverändert: \n{neu}")



Kopie ist: 
[[[   1    2    3    4    5]
  [   6    7    8    9   10]
  [  11   12   23   45   17]]

 [[  -1   -2   -3   -4   -5]
  [  -6   -7   -8   -9  -10]
  [ -11  -12  -23  -45  -17]]

 [[-100 -200 -300 -400 -500]
  [-600 -700 -800 -900 -110]
  [-111 -112 -123 -145 -117]]]
veränderte Kopie ist jetzt: 
[[[     1      2      3      4      5]
  [     6      7      8      9     10]
  [    11     12     23     45     17]]

 [[    -1     -2     -3     -4     -5]
  [    -6     -7     -8     -9    -10]
  [-10000 -10000 -10000 -10000 -10000]]

 [[  -100   -200   -300   -400   -500]
  [  -600   -700   -800   -900   -110]
  [  -111   -112   -123   -145   -117]]]
Originalarray ist unverändert: 
[[[   1    2    3    4    5]
  [   6    7    8    9   10]
  [  11   12   23   45   17]]

 [[  -1   -2   -3   -4   -5]
  [  -6   -7   -8   -9  -10]
  [ -11  -12  -23  -45  -17]]

 [[-100 -200 -300 -400 -500]
  [-600 -700 -800 -900 -110]
  [-111 -112 -123 -145 -117]]]
Originalarray ist verändert: 
[[[   

NumPy Arrays kann man also mit np.copy(array_name) oder array_name.copy() kopieren. Es gibt einen zweiten optionalen Parameter beim Kopieren. Dieser gibt die Ordnung des Array im Speicher an, was wichtig sein kann, wenn man diesen Speicherinhalt in anderen Sprachen gebrauchen will. Möglich ist neben anderen speziellen Zeichen z.B. "C" oder "F", damit wird der Speicherbereich angelegt, wie es einem C-Array oder einem Fortran-Array entspricht.

NumPy unterscheidet bei Kopieraktionen zwischen Ansichten eines Arrays (Views), die sehr schnell und Speicher-effizient ablaufen und echten Kopien. Ändert man solche Views, wird entsprechend auch das Originalarray verändert.  Bei echten Kopien werden neue Arrays angelegt, die völlig unabhängig vom Originalarray sind, natürlich mit entsprechendem Zeit- und Speicherbedarf. Ein typisches Beispiel für die Erzeugung eines View ist unten gezeigt, indem wir über den Teilbereichsoperator eine solche erzeugen. Wir erkennen, dass die View und das Originalarray verknüpft sind. 

In [30]:
import numpy as np
orig = np.arange(10)
print(f"Originalarray: {orig}")

view = orig[1:5]  # Dieses macht eine View
print(f"View: {view}")
orig[1:3] = [-10, -11]
print(f"Originalarray wurde verändert und ist jetzt: {orig}")

print(f"View ist auch verändert: {view}")


Originalarray: [0 1 2 3 4 5 6 7 8 9]
View: [1 2 3 4]
Originalarray wurde verändert und ist jetzt: [  0 -10 -11   3   4   5   6   7   8   9]
View ist auch verändert: [-10 -11   3   4]


Machen wir jetzt ein 2-dim Array und schneiden hier Teile aus, <b>wird eine unabhängige Kopie angelegt, wenn wir hierzu sogenanntes "advanced indexing" also fortgeschrittenen Indexzugriff durchführen mit einem Teilbereichsoperator über alle Dimensionen.</b> Dabei kann man neben unserer bekannten Schreibweise auch die auszuschneidenden Bereich als Tupel angeben wie unten gezeigt.

In [79]:
my_array = np.arange(10, 1, -1)
print(my_array)

ausschnitt = my_array[np.array([3, 3, 1, 8])]
print(ausschnitt)


[10  9  8  7  6  5  4  3  2]
[7 7 9 2]


Auf identische Weise können die auszuschneidenden Elemente auch als Tupel oder Liste an ihrer jeweiligen Stelle im Teilbereichsoperator angegeben werden.``` array[:,(1,2)]``` bedeutet also alle Zeilen und die Spalten 1 und 2.<br> 

Im unteren Beispiel könnten wir ebenso unsere bekannte Schreibweise ``` array[:,1:3]``` verwenden. Weder hat eine Veränderung des Originalarrays auf das neu erzeugte Ausschnittsarray einen Einfluss als auch umgekehrt keine Verknüpfung besteht.

In [66]:
orig1 = np.array( [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        ])

print(f"Originalarray:\n {orig1}")
ausschnitt = orig1[:,(1,2)]

print(f"zweite und dritte Spalte wurde ausgeschnitten: \n {ausschnitt}")
ausschnitt[1]=-10000
print(f"Ausschnitt wurde verändert auf:\n {ausschnitt}")
print(f"Originalarray jetzt unverändert:\n {orig1}")
print(60*"=")

ausschnitt2 = orig1[:,1:3]
print(f"zweite und dritte Spalte wurde ausgeschnitten: \n {ausschnitt2}")
orig[2][2]=-1000
print(f"Originalarray wurde verändert auf:\n {orig}")
print(f"View ist nicht verändert:\n {ausschnitt2}")


Originalarray:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
zweite und dritte Spalte wurde ausgeschnitten: 
 [[ 2  3]
 [ 7  8]
 [12 13]]
Ausschnitt wurde verändert auf:
 [[     2      3]
 [-10000 -10000]
 [    12     13]]
Originalarray jetzt unverändert:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
zweite und dritte Spalte wurde ausgeschnitten: 
 [[ 2  3]
 [ 7  8]
 [12 13]]
Originalarray wurde verändert auf:
 [[    0     1     2     3     4]
 [    5     6     7     8     9]
 [   10    11 -1000    13    14]]
View ist nicht verändert:
 [[ 2  3]
 [ 7  8]
 [12 13]]


### einfache Matrizen Operationen
Oft werden in der linearen Algebra Identitätsmatrizen benötigt, die wir als quadratische zeidimensionale NumPy-Arrays abbilden können, und deren Werte bis auf die Diagonale, wo sie mit dem Wert 1 besetzt sind, alle 0 sind. NumPY bietet eine komfortable Möglichkeit diese zu erstellen mit der np.identity(k,dtype=...) Methode. Diese hat einen obligaten Parameter k, der die Seitenlänge der quadratischen Matrix angibt, ausserdem kann der dtype angegegben werden.

In [81]:
print(np.identity(6,dtype = int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


Für nicht quadratische Arrays oder Matrizen gibt es die etwas komplexere np.eye Methode mit folgender Syntax:<br> ```eye(N, M=None, k=0, dtype=float)```. Dabei gibt N die Anzahl der Zeilen an, M die Anzahl der Spalten (falls sie von N abweichen , sonst N), k sagt aus weche Diagonale gemeint ist, bei 0 als Default-Wert ist es die Hauptdiagonale bei negativen Werten wird die Diagonale um k Spalten nach links verschoben, bei positiven Werten nach rechts.

In [89]:
print(f" np.eye(5,8,-2): \n {np.eye(5,8,-2)}\n")
print(f" np.eye(5,8,2): \n {np.eye(5,8,2)}\n")
print(f" np.eye(5): \n {np.eye(5)}\n")

 np.eye(5,8,-2): 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]

 np.eye(5,8,2): 
 [[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]

 np.eye(5): 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



Ausserdem lassen sich Arrays einfach transponieren, also entlang der Diagonalen umdrehen mit ```np.transpose(array,axes = None)```. Gibt man den axes Parameter nicht an, wird entlang der Diagonalen transponiert. Im axes-Parameter kann die Reihenfolge der Achsen angegeben werden, die die Ordnung des transponierten Arrays beschreibt. Im unteren 3D Beispiel haben wir die Reihenfolge der Achsen auf (1,0,2) gesetzt. Die Elemente entsprechen in ihrem Wert ZeileSpalteEbene des Originalarrays. Alle Achsen müssen jeweils einmal in dem axes-Tupel vorkommen, die Reihenfolge entscheidet über die Art der Transposition. Wir haben unten alle Möglichkeiten für 3 Achsen dargestellt. Die Permutationen haben wir mit dem itertools Modul erstellt mit itertools.permutations([0,1,2],3), als da sind: [(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)].

In [118]:
import itertools
orig1 = np.array( [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        ])
print(orig1)
orig2 = np.transpose(orig1)#axes=([1,0]))
print("="*60)
print(orig2)
print("="*60)
perms = list(itertools.permutations([0,1,2],3))
print(f"Permuationen der Achsen: {perms} \n")
             
drei_dim = np.array([
                        [
                        ["000","010","020","030","040"],
                        ["100","110","120","130","140"],
                        ["200","210","220","230","240"],
                        ],
                        [
                        ["001","011","021","031","041"],
                        ["101","111","121","131","141"],
                        ["201","211","221","231","241"],
                        ],
                        [
                        ["002","012","022","032","042"],
                        ["102","112","122","132","142"],
                        ["202","212","222","232","242"],
                        ]
                    ])
print("Original")
for perm in perms:
    print(f" {str(perm)} :\n {np.transpose(drei_dim,axes = perm)}")
    print("="*60)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
Permuationen der Achsen: [(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)] 

Original
 (0, 1, 2) :
 [[['000' '010' '020' '030' '040']
  ['100' '110' '120' '130' '140']
  ['200' '210' '220' '230' '240']]

 [['001' '011' '021' '031' '041']
  ['101' '111' '121' '131' '141']
  ['201' '211' '221' '231' '241']]

 [['002' '012' '022' '032' '042']
  ['102' '112' '122' '132' '142']
  ['202' '212' '222' '232' '242']]]
 (0, 2, 1) :
 [[['000' '100' '200']
  ['010' '110' '210']
  ['020' '120' '220']
  ['030' '130' '230']
  ['040' '140' '240']]

 [['001' '101' '201']
  ['011' '111' '211']
  ['021' '121' '221']
  ['031' '131' '231']
  ['041' '141' '241']]

 [['002' '102' '202']
  ['012' '112' '212']
  ['022' '122' '222']
  ['032' '132' '232']
  ['042' '142' '242']]]
 (1, 0, 2) :
 [[['000' '010' '020' '030' '040']
  ['001' '011' '021' '031' '041']
  ['002' '012' '022' '0