## Arithmetische Rechenoperationen mit NumPy - Arrays
<br><img width= 400 src="images/Arithmetik.jpg" />
<br>"Designed by Freepik"

Mit NumPy Arrays lassen sich elegant und schnell numerische Operationen durchführen. Unsere gewohnten mathematischen Operatoren sind für NumPy - Arrays überladen und deshalb einfach anwendbar. Zunächst ein Beispiel einer elementweisen (skalaren) Addition. Wir haben ausserdem den Typ des Ergebnisarrays mit der astype(np.int) Methode in Integer verwandelt.

In [4]:
import numpy as np
test_array = np.array([2.3,4.1,8.2])
result_array = (test_array + 10).astype(np.int)
print(result_array)

[12 14 18]


Natürlich geht dies auch für unsere anderen arithmetischen Operatoren wie -,*,/ und $**$, sowie // und %. Auch die round() Methode können wir natürlich benutzen, wir müssen sie aber mit np.round ansprechen.

In [20]:
test_array = np.array([2.33,4.71,8.23])
print("Originalarray",test_array)
result_array = ("-10",test_array - 10)
print(result_array)
result_array = ("*10",test_array * 10)
print(result_array)
result_array = ("/10",test_array / 10)
print(result_array)
result_array = ("**10",test_array ** 10)
print(result_array)
result_array = (test_array*10).astype(int)
print(result_array,"Ganzzahldivision durch 5",result_array//5)
print(result_array,"modulo 5",result_array%5)
result_array = ("/10 auf 1 Stelle gerundet",np.round(test_array / 10,1))
print(result_array)

Originalarray [2.33 4.71 8.23]
('-10', array([-7.67, -5.29, -1.77]))
('*10', array([23.3, 47.1, 82.3]))
('/10', array([0.233, 0.471, 0.823]))
('**10', array([4.71584161e+03, 5.37290388e+06, 1.42560218e+09]))
[23 47 82] Ganzzahldivision durch 5 [ 4  9 16]
[23 47 82] modulo 5 [3 2 2]
('/10 auf 1 Stelle gerundet', array([0.2, 0.5, 0.8]))


Um ähnliche Operationen im Kernpython durchzuführen, müssen wir über unseren kombinierten Datentyp iterieren wie z.B. mit einer Listenabstraktion :

In [23]:
my_list = [2.33,4.71,8.23]
print("original ",my_list)
print("*10 ",[10 * elem for elem in my_list])

original  [2.33, 4.71, 8.23]
*10  [23.3, 47.1, 82.30000000000001]


Nicht nur ist NumPy hier viel eleganter, sondern auch deutlich schneller mit dem Faktor von ca. 40 für die Bearbeitung einer Aufzählung von 10000 Werten mit einer elemtweisen Multiplikation.

In [55]:
from timeit import Timer

my_list = list(range(1000))
timer_obj1 = Timer("[10 * elem for elem in my_list]","from __main__ import  my_list")
print(f"Listenabstraktion: {timer_obj1.timeit(10000)} s")
test_array = np.arange(0,1000)
timer_obj2 = Timer("test_array*10","from __main__ import  test_array")
print(f"Numpy Skalar-Multiplikation: {timer_obj2.timeit(10000)} s")



Listenabstraktion: 0.3933486000000812 s
Numpy Skalar-Multiplikation: 0.010214000000360102 s


Natürlich können wir auch zwei gleichförmige Arrays arithmetisch elementweise verknüpfen.

In [57]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[2,2,2],
              [6,10,12]])
print(a*b)

[[ 3  4  5]
 [10 15 18]]


In der Mathematik benötigt man aber auch oft nicht die elementweise Multiplikation von Matrizen, sondern das "innere Produkt" oder "dot-Produkt". Für Skalare oder eindimensionale Arrays (Vektoren) entspricjt es der elementweisen Multiplikation.

In [ ]:
a = np.array(5)
b = n